#alias ls='ls --show-control-chars -F --color $*'
alias ls='ls -l -a'
alias ll='ls -l --color=tty'
alias base='cd ~/zs_1.0/frameworks/base'
alias ui='cd ~/zs_1.0/frameworks/base/packages/SystemUI'
alias c='cd'
alias b='cd ..'
alias h='cd ~'
alias zs='cd ~/zs_1.0'
alias common='cd ~/zs_1.0/device/zeusis/common'
alias 3app='cd ~/zs_1.0/vendor/coolyota/ThridApp'
alias Y3='cd ~/zs_1.0/device/zeusis/Y3'
alias log='cd ~/zs_1.0/vendor/coolyota/app/CY_Log_Reporter'
alias theme='cd ~/zs_1.0/vendor/zeusis/app/ZsThemeManager'
alias mart='cd ~/zs_1.0/vendor/zeusis/prebuilt/coolmart'
alias priv='cd ~/zs_1.0/out/target/product/Y3/system/priv-app'
alias sett='cd ~/zs_1.0/packages/apps/Settings'
alias ali="vim ~/.bash_aliases"
alias bash="source ~/.bashrc"
alias ui="cd d:/0Work/UI"

alias cl='clear'
#alias g='git'
alias gst='git status'
alias st='status'
alias ga='git add .'
alias gba='git branch -a'
alias gbv='git branch -vv'
alias gf='git fetch'
alias gr='git rebase'
alias grv='git remote -v'
alias gp='git push'
alias gco='git checkout'
alias gcm='git commit -a -s'
alias gamend=git commit --amend -C HEAD 
alias gcl='git config --list'
alias gl='git log'
alias gla='git log --oneline --all --graph --decorate  $*'
alias gl1='git log --oneline --graph --decorate --color=always'
alias gll='git log -prerry=oneline'

alias o='explorer .'

